/* Generated By:JavaCC: Do not edit this line. SchemaParserConstants.java */
/**  
 * Copyright (c) 1998-2005, Verge Lab., LLC.
 * All rights reserved.
 */
package org.safehaus.penrose.schema;

public interface SchemaParserConstants {

  int EOF = 0;
  int TRAILING_COMMENT = 5;
  int LPAREN = 6;
  int RPAREN = 7;
  int LBRACE = 8;
  int RBRACE = 9;
  int LBRACKET = 10;
  int RBRACKET = 11;
  int DOT = 12;
  int DOLLAR = 13;
  int QUOTE = 14;
  int NAME = 15;
  int DESC = 16;
  int OBSOLETE = 17;
  int SUP = 18;
  int EQUALITY = 19;
  int ORDERING = 20;
  int SUBSTR = 21;
  int SYNTAX = 22;
  int SINGLE_VALUE = 23;
  int COLLECTIVE = 24;
  int NO_USER_MODIFICATION = 25;
  int USAGE = 26;
  int OBJECTCLASS = 27;
  int ATTRIBUTETYPE = 28;
  int ABSTRACT = 29;
  int STRUCTURAL = 30;
  int AUXILIARY = 31;
  int MUST = 32;
  int MAY = 33;
  int USER_APPLICATIONS = 34;
  int DIRECTORY_OPERATION = 35;
  int DISTRIBUTED_OPERATION = 36;
  int DSA_OPERATION = 37;
  int DIGIT = 38;
  int IDENT = 39;
  int QDSTRING = 40;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<TRAILING_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"$\"",
    "\"\\\'\"",
    "\"NAME\"",
    "\"DESC\"",
    "\"OBSOLETE\"",
    "\"SUP\"",
    "\"EQUALITY\"",
    "\"ORDERING\"",
    "\"SUBSTR\"",
    "\"SYNTAX\"",
    "\"SINGLE-VALUE\"",
    "\"COLLECTIVE\"",
    "\"NO-USER-MODIFICATION\"",
    "\"USAGE\"",
    "<OBJECTCLASS>",
    "<ATTRIBUTETYPE>",
    "\"ABSTRACT\"",
    "\"STRUCTURAL\"",
    "\"AUXILIARY\"",
    "\"MUST\"",
    "\"MAY\"",
    "\"userApplications\"",
    "\"directoryOperation\"",
    "\"distributedOperation\"",
    "\"dSAOperation\"",
    "<DIGIT>",
    "<IDENT>",
    "<QDSTRING>",
  };

}
