/* Generated By:JavaCC: Do not edit this line. ItemParserConstants.java */
/**
 * Copyright (c) 2000-2006, Identyx Corporation.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
package org.safehaus.penrose.filter.item;

public interface ItemParserConstants {

  int EOF = 0;
  int ANY = 4;
  int COLON = 5;
  int SPACE = 6;
  int TYPE = 7;
  int MATCHINGRULE = 8;
  int DIGIT = 9;
  int ATTR = 10;
  int VALUE = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"*\"",
    "\":\"",
    "\" \"",
    "<TYPE>",
    "<MATCHINGRULE>",
    "<DIGIT>",
    "<ATTR>",
    "<VALUE>",
  };

}
