#!/bin/bash
#
# penrose-monitor This shell script takes care of starting and stopping ${product.title} Monitor.
#
# chkconfig: - 38 62
# description: ${product.title} Monitor ${product.version}.
# processname: java
# pidfile: /usr/local/${module.name}-${product.version}/logs/penrose-monitor.pid

# Source function library.
. /etc/init.d/functions

# Source networking configuration and check that networking is up.
if [ -r /etc/sysconfig/network ] ; then
	. /etc/sysconfig/network
	[ ${NETWORKING} = "no" ] && exit 0
fi

# Source an auxiliary options file if we have one.
if [ -r /etc/sysconfig/penrose ] ; then
	. /etc/sysconfig/penrose
fi

PENROSE_HOME=/usr/local/${module.name}-${product.version}
PENROSE_MONITOR_SCRIPT=$PENROSE_HOME/bin/penrose-monitor.sh

PENROSE_MONITOR_PROG=penrose-monitor
PENROSE_USER=root

[ -x $PENROSE_MONITOR_SCRIPT ] || exit 0

RETVAL=0

function start() {
        # Start daemons.
        echo -n $"Starting $PENROSE_MONITOR_PROG: "
        daemon --user $PENROSE_USER $PENROSE_MONITOR_SCRIPT start
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/penrose-monitor
	return $RETVAL
}

function stop() {
        # Stop daemons.
	echo -n $"Stopping $PENROSE_MONITOR_PROG: "
        daemon --user $PENROSE_USER $PENROSE_MONITOR_SCRIPT stop
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/penrose-monitor /var/run/penrose-monitor.args
	return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $PENROSE_MONITOR_PROG
	;;
    restart)
	stop
	start
	;;
    reload)
    	killproc $PENROSE_MONITOR_PROG -HUP
	RETVAL=$?
	;;
    condrestart)
        if [ -f /var/lock/subsys/penrose-monitor ] ; then
            stop
            start
        fi
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status|condrestart}"
	RETVAL=1
esac

exit $RETVAL
