/* Generated By:JavaCC: Do not edit this line. ItemParserConstants.java */
/**
 * Copyright (c) 1998-2005, Verge Lab., LLC.
 * All rights reserved.
 */
package org.safehaus.penrose.filter.item;

public interface ItemParserConstants {

  int EOF = 0;
  int ANY = 4;
  int COLON = 5;
  int SPACE = 6;
  int TYPE = 7;
  int MATCHINGRULE = 8;
  int DIGIT = 9;
  int ATTR = 10;
  int VALUE = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"*\"",
    "\":\"",
    "\" \"",
    "<TYPE>",
    "<MATCHINGRULE>",
    "<DIGIT>",
    "<ATTR>",
    "<VALUE>",
  };

}
