#!/bin/bash
#
# penrose This shell script takes care of starting and stopping penrose server.
#
# chkconfig: - 38 62
# description: Penrose Virtual Directory Server.
# processname: java
# pidfile: /var/run/penrose.pid

# Source function library.
. /etc/init.d/functions

# Source networking configuration and check that networking is up.
if [ -r /etc/sysconfig/network ] ; then
	. /etc/sysconfig/network
	[ ${NETWORKING} = "no" ] && exit 0
fi

# Source an auxiliary options file if we have one.
if [ -r /etc/sysconfig/penrose ] ; then
	. /etc/sysconfig/penrose
fi

penrose=/usr/local/penrose/bin/penrose.sh

[ -x ${penrose} ] || exit 0

RETVAL=0

function start() {
        # Start daemons.
	prog=`basename ${penrose}`
        echo -n $"Starting $prog: "
        daemon ${penrose}
	RETVAL=$?
        echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/penrose
	return $RETVAL
}

function stop() {
        # Stop daemons.
	prog=`basename ${penrose}`
	echo -n $"Stopping $prog: "
	killproc ${penrose}
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/penrose /var/run/penrose.args
	return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${penrose}
	;;
    restart)
	stop
	start
	;;
    reload)
    	killproc ${penrose} -HUP
	RETVAL=$?
	;;
    condrestart)
        if [ -f /var/lock/subsys/penrose ] ; then
            stop
            start
        fi
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status|condrestart}"
	RETVAL=1
esac

exit $RETVAL
