/* Generated By:JavaCC: Do not edit this line. SlapdParserConstants.java */
/**
 * Copyright (c) 1998-2005, Verge Lab., LLC.
 * All rights reserved.
 */
package org.safehaus.penrose.openldap.config;

public interface SlapdParserConstants {

  int EOF = 0;
  int NAME = 1;
  int VALUE = 2;
  int QDVALUE = 3;
  int WS = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<NAME>",
    "<VALUE>",
    "<QDVALUE>",
    "<WS>",
  };

}
